apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cu3f6bjfe-nodejs 
  janus-idp.io/tekton: cu3f6bjfe-nodejs
  backstage.io/kubernetes-id: cu3f6bjfe-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cu3f6bjfe-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  