apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cu3f6bjfe-nodejs
  janus-idp.io/tekton: cu3f6bjfe-nodejs
  backstage.io/kubernetes-id: cu3f6bjfe-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cu3f6bjfe-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
