apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cu3f6bjfe-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cu3f6bjfe-nodejs 
  name: cu3f6bjfe-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cu3f6bjfe-nodejs 
